[
build
]
builder = "nixpacks"
buildCommand = "php artisan storage:link"

[
deploy
]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"